version: '3.3'

services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db01
      network: internal
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    links:
      - "db"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    restart: always
    volumes:
      - prom
  

  psqlexporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://root:toor@db:5432/db01?sslmode=disable"
  
  nocodb:
    image: nocodb/nocodb:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./nc_data:/usr/app/data
    links:
      - "db"
    environment:
      NC_DB: "pg://db:5432?u=root&p=toor&d=db01"

  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: tooljet/.env
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 8083:80
      - 4443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: tooljet/.env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  grafana:
    image: grafana/grafana-oss:latest
    ports: 
      - 8082:3000
    

networks:
  internal:
  
volumes:
  prom:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
  certs:
  logs:
  fallbackcerts:
